# -*- coding: utf-8 -*-
"""Heart-Disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFTD_N4eozZ383by_jxwOpNad63WG6Bx
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pickle

clf=RandomForestClassifier(n_estimators=100)

data=pd.read_csv('/heart-disease.csv')
X = data.drop('target', axis=1)
y=data['target']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

print(clf.fit(X_train,y_train))
y_pred= clf.predict(X_test)
print(y_pred)

q=clf.score(X_train,y_train)
print(q)
w=clf.score(X_test,y_test)
print(w)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

np.random.seed(42)
for i in range(10,100,10):
    print(f'trying model with {i} estimators....')
    clf=RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(f'Model accuracy on test set: {clf.score(X_test,y_test)}')

pickle.dump(clf,open('random forest model', 'wb'))